<?xml version="1.0" encoding="utf-8"?><Database Name="QL_Music" Class="QLMusicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-NGUYENS\SQLEXPRESS;Initial Catalog=QL_Music;User ID=sa" SettingsObjectName="DAL_BLL.Properties.Settings" SettingsPropertyName="QL_MusicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaiHat" Member="BaiHats">
    <Type Name="BaiHat">
      <Column Name="maBaiHat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenBaiHat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maCaSi" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="pathBaiHat" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="BaiHat_BaiHatVaPlayList" Member="BaiHatVaPlayLists" ThisKey="maBaiHat" OtherKey="maBaiHat" Type="BaiHatVaPlayList" />
    </Type>
  </Table>
  <Table Name="dbo.Playlist" Member="Playlists">
    <Type Name="Playlist">
      <Column Name="maPlaylist" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenPlaylist" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Playlist_BaiHatVaPlayList" Member="BaiHatVaPlayLists" ThisKey="maPlaylist" OtherKey="maPlaylist" Type="BaiHatVaPlayList" />
    </Type>
  </Table>
  <Table Name="dbo.BaiHatVaPlayList" Member="BaiHatVaPlayLists">
    <Type Name="BaiHatVaPlayList">
      <Column Name="maBaiHat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPlaylist" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="BaiHat_BaiHatVaPlayList" Member="BaiHat" ThisKey="maBaiHat" OtherKey="maBaiHat" Type="BaiHat" IsForeignKey="true" />
      <Association Name="Playlist_BaiHatVaPlayList" Member="Playlist" ThisKey="maPlaylist" OtherKey="maPlaylist" Type="Playlist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaSi" Member="CaSis">
    <Type Name="CaSi">
      <Column Name="maCaSi" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenCaSi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>